
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./certs:/etc/ssl/certs
    ports:
      - "8000:8000"
    container_name: goalStatApi
    depends_on:
      - redis
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: "redis:alpine"  


  worker:
    build: .
    volumes:
      - ./app:/app
      - ./certs:/etc/ssl/certs
    depends_on:
      - redis
    command: ["celery", "-A", "tasks", "worker", "-B","--loglevel=info"]
  
  flower:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    command: celery -A tasks flower --broker=redis://redis:6379/0
    
