
services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./certs:/etc/ssl/certs
    ports:
      - "8000:8000"
    container_name: goalStatApi
    depends_on:
      - redis
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: "redis:alpine"  
    ports:
      - "6379:6379"


  worker:
    build: .
    volumes:
      - ./app:/app
      - ./certs:/etc/ssl/certs
    depends_on:
      - redis
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    
