name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Запускать при изменении в ветке main
  pull_request:
    branches:
      - main   # Запускать при pull запросах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

          
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
        run: |
          docker build -t your-docker-username/your-image:latest .

      - name: Push Docker Image
        run: |
          docker push your-docker-username/your-image:latest

      - name: Pull Docker Image
        run: |
          docker pull your-docker-username/your-image:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose up -d
