name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Запускать при изменении в ветке main
  pull_request:
    branches:
      - main   # Запускать при pull запросах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        volumes:
          - postgres_data:/var/lib/postgresql/data
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: |
        docker build -t myusername/myapp:${{ github.sha }} .
      
    - name: Push image to Docker Hub
      run: |
        docker push myusername/myapp:${{ github.sha }}

    - name: Deploy to Server
      env:
        DOCKER_HOST: ssh://user@yourserver.com
      run: |
        ssh user@yourserver.com "docker pull myusername/myapp:${{ github.sha }} && docker-compose up -d"

volumes:
  postgres_data:
