name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Запускать при изменении в ветке main
  #pull_request:
    #branches:
     # - main   # Запускать при pull запросах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t varkkosh/goalstatapi:latest .

      - name: Push Docker Image
        run: |
          docker push varkkosh/goalstatapi:latest

      - name: Pull Docker Image
        run: |
          docker pull varkkosh/goalstatapi:latest

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/${{ secrets.SERVER_USER }}/git/GoalStatsApi
            git pull origin main
            docker run -d -p 8000:8000 varkkosh/goalstatapi:1.0
          EOF

