name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Запускать при изменении в ветке main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Set up SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          #key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
             cd /home/${{ secrets.SERVER_USER }}/git/GoalStatsApi
             git pull origin main
             docker-compose up --build
