name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Запускать при изменении в ветке main
  #pull_request:
    #branches:
     # - main   # Запускать при pull запросах в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build and run Docker on server
      run: |
        ssh -o StrictHostKeyChecking=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 

